name: pytest

inputs:
  python-version:
    required: true
  python-cache-version:
    required: false
    default: '1'
  python-requirements:
    required: false

runs:
  using: composite
  steps:
    - name: Install Python
      id: python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    - name: Cache Python packages
      id: cache-python
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-${{ steps.python.outputs.python-version }}-python-${{ inputs.python-cache-version }}
    - name: Install pytest
      shell: bash
      run: python -m pip install --upgrade --upgrade-strategy eager pytest ${{ inputs.python-requirements }}
    - name: Run tests
      shell: bash
      run: pytest tests
