name: prek

runs:
  using: composite
  steps:
    - name: Install Python
      uses: actions/setup-python@v6.2.0
      with:
        python-version-file: "pyproject.toml"
        check-latest: true
    - name: Run prek
      uses: j178/prek-action@v2.0.2
